spring:
  #H2 DataBase 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:tothebook                         # H2 DB 연결 주소 (인메모리)
    username: sa                                       # H2 DB 접속 ID
    password:                                          # H2 DB 접속 패스워드

  # H2 콘솔 설정
  h2:
    console:
      enabled: true             # H2 콘솔 사용 여부
      path: /h2-console         # H2 접속 경로
      settings:
        web-allow-others: true  # H2 외부 접속 허용 여부

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create # 또는 validate (create 사용해도 되려면 개발 끝나기 전 entity 제대로 만든 후 적용)
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  # thymeleaf 설정
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    #cache: false 타임리프 소스 변경 시 서버를 재시작 하지 않아도 적용해줌. (배포 시 true로 변경할 것)

  mail:
    host: smtp.naver.com # 구글 계정 만들기까지 네이버 계정 사용
    port: 587
    username: id
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# log 설정
logging:
  level:
    root: info
    com.std.tothebook.api: debug
    org.hibernate.SQL: debug
  file:
    #path: logs
    name: logs/tothebookLog.log
  pattern:
    console: "%-5level %d{yyyy-MM-dd HH:mm:ss}[%thread] [%logger{0}:%line] - %msg%n"
    file: "%-5level %d{yy-MM-dd HH:mm:ss}[%thread] [%logger{0}:%line] - %msg%n"

  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log # by tothebookLog.20230619.1.log
      clean-history-on-start: true
      max-file-size: 10MB # 파일 최대 사이즈
      max-history: 30     # 파일 최대 개수

# swagger 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    # groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**

# jwt
jwt:
  key: wuc7+P1EsZRQTgFha2y/TKJORNFmacS24V2uSvCCG2IEAvbe3dRg1FjA02PHyqV5PYaiuK+kh4WvOowaDoRKR3KweWtA8O/C
  expired-time: 120000 # 2분
  refresh-expired-time: 600000 # 10분

# 인증
certification:
  limited-minutes: 5

api:
  aladin:
    key: ENC(qtKDaS9b8kzqHSTD8pg8d1GAnJevQdbG)
    version : 20131101
    response_type : js

# regex
regex:
  email: "^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*.[a-zA-Z]{2,3}$"
  password: "^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*#?&])[A-Za-z\\d@$!%*#?&]{10,}$"

# 정책
policy:
  nickname-duplicate-check-days: 30
  password-length: 10
